from typing import TypedDict
from langchain_core.documents import Document
from langgraph.graph import StateGraph, START, END


class RAGState(TypedDict):
    """
    RAGState is a dictionary that holds the state of a RAG (Retrieval-Augmented Generation) model.
    It contains the following keys:
    - 'question': The original question that was used to retrieve documents.
    - 'retrieved_chunks': A list of chunks retrieved from the knowledge base.
    - 'response': The text generated by the model based on the retrieved chunks.
    """
    question : str
    retrieved_chunks : list[Document]
    response : str
    
def make_retrieve_node(store, k:int = 3):
    def retrieve(state : RAGState) -> dict:
        question = state["question"]
        chunks = store.similarity_search(question, k=k)
        return {"retrieved_chunks" : chunks}  
    return retrieve


def make_generate_node(llm): 
    def generate(state: RAGState) -> dict : 
        question = state["question"]
        chunks = state["retrieved_chunks"]
        parts = []
        for chunk in chunks : 
            parts .append(chunk.page_content)
        context =  "\n\n".join(parts)
        
        message = [
            ("system", "Answer questions about the LangChain documentation based solely on the context provided. If the context does not contain the answer, say, 'I don't have the answer to that question.'"),
            ("human", question + "\n\n" + context)
        ]
        response = llm.invoke(message).content
        
        return {"response" : response}
    
    return generate


def build_rag_graph(store, llm, k: int = 3):
    """
    Builds a RAG (Retrieval-Augmented Generation) graph using the provided store and LLM (Language Model).
    
    Args:
        store: The knowledge store used for retrieving relevant chunks.
        llm: The language model used for generating responses.
        k: The number of chunks to retrieve from the store (default is 3). 
    
    Returns:
        The compiled RAG graph, ready to be invoked.    
    
    """
    
    builder = StateGraph(RAGState)
    
    builder.add_node("retrieve", make_retrieve_node(store, k))
    builder.add_node("generate", make_generate_node(llm))
    
    builder.add_edge(START, "retrieve")
    builder.add_edge("retrieve", "generate")
    builder.add_edge("generate", END)
    
    return builder.compile()